### ISSUE TITLE
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

### ISSUE THREAD

**Issue by kh4n9373** [ML-K67-HUST/MUSIC-GENRE-CLASSIFICATION_PROJ#18]
Technical suggestion from the kernel:

![image](https://github.com/ML-K67-HUST/MUSIC-GEN-PROJ/assets/112315454/ea1c69b2-4f95-4fe2-92a0-a29875739fee)

Would the performance of the model increase if we take into account the suggestion ?

**Comment by KienDinhVan** [comment]
Done

**Comment by ktuanPT373** [comment]
Hay e
